services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: baitap_todoapp_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/${MONGO_DB_NAME}
    networks:
      - baitap_todoapp
    depends_on:
      - db

  db:
    image: mongo
    container_name: baitap_todoapp_db
    ports:
      - "27018:27017"
    volumes:
      - ./docker/db/data:/data/db
    networks:
      - baitap_todoapp

networks:
  baitap_todoapp:
      driver: bridge
